---
  - name: "List existing VGs to be able to guess which one we are going to use"
    command:
      vgs
    register: vgs_cmd
  - name: "Guess VG name we are going to use"
    set_fact:
      main_vg: "{{ item }}"
    when: "main_vg is not defined and item in vgs_cmd.stdout"
    with_items:
      - "rhel_{{ inventory_hostname_short }}"
      - "vg_{{ inventory_hostname_short }}"
  - name: "Make sure we have guessed VG name"
    assert:
      that: "main_vg is defined"

  - name: "List existing LVs to be able to guess which one we are going to use"
    command:
      lvs
    register: lvs_cmd
  - name: "Guess LV name we are going to use"
    set_fact:
      main_lv: "{{ item }}"
    when: "main_lv is not defined and item in lvs_cmd.stdout"
    with_items:
      - "lv_root"
      - "root"
  - name: "Make sure we have guessed LV name"
    assert:
      that: "main_lv is defined"

  - name: "Extend root LV to all available VG space"
    lvol:
      vg: "{{ main_vg }}"
      lv: "{{ main_lv }}"
      size: +100%FREE
  - name: "Extend root filesystem to whole LV"
    filesystem:
      dev: "/dev/{{ main_vg }}/{{ main_lv }}"
      fstype: xfs
      resizefs: yes
...
