- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - ec2:
        key_name: my_key
        group: test
        instance_type: r3.8xlarge
        image: "{{ ami_id }}"
        wait: true
        exact_count: 1
        count_tag:
          Name: Satellite
        instance_tags:
          Name: Satellite
      register: ec2
   - add_host: hostname={{ item.public_ip }} groups=satellite
     with_items: ec2.instances

    - ec2:
        key_name: my_key
        group: test
        instance_type: m4.4xlarge
        image: "{{ ami_id }}"
        wait: true
        exact_count: 50
        count_tag:
          Name: Capsules
        instance_tags:
          Name: Capsules
      register: ec2
   - add_host: hostname={{ item.public_ip }} groups=capsules
     with_items: ec2.instances

    - ec2:
        key_name: my_key
        group: test
        instance_type: m4.4xlarge
        image: "{{ ami_id }}"
        wait: true
        exact_count: 10
        count_tag:
          Name: DockerHosts
        instance_tags:
          Name: DockerHosts
      register: ec2
   - add_host: hostname={{ item.public_ip }} groups=docker-hosts
     with_items: ec2.instances

    - ec2:
        key_name: my_key
        group: test
        instance_type: m4.10xlarge
        image: "{{ ami_id }}"
        wait: true
        exact_count: 1
        count_tag:
          Name: Monitor
        instance_tags:
          Name: Monitor
      register: ec2
   - add_host: hostname={{ item.public_ip }} groups=monitor
     with_items: ec2.instances
