---
- hosts: docker-hosts
  remote_user: root
  roles:
    - rhsm
    - common
  tasks:
    - command:
        subscription-manager repos --enable 'rhel-7-server-extras-rpms'
    - yum:
        name=docker
        state=present
    - service:
        name=docker
        state=running
        enabled=yes
    - command:
        docker pull jhutar/katello-client:rhel-6.7
