---
- hosts: satellite
  remote_user: root
  roles:
    - common
    - pbench_client
  vars:
    orgid=1
    releasever="6Server"
    product1="Red Hat Enterprise Linux Server"
    product2="Red Hat Enterprise Linux Server"
    product3="Red Hat Software Collections for RHEL Server"
    reposet1="Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server RPMs"
    reposet2="Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server - RH Common RPMs"
    reposet3="Red Hat Software Collections RPMs for Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server"
  tasks:
    - copy: src="{{ sat_repo_file }}" dest=/etc/yum.repos.d/

    - redhat_subscription:
        state=present
        username="{{ rhsm_user }}"
        password="{{ rhsm_pass }}"
        pool="{{ rhsm_pools }}"
        autosubscribe=true
      register: registration
    - shell: |
        subscription-manager repos --disable 'rh*'
        subscription-manager repos --enable 'rhel-{{ ansible_distribution_major_version }}-server-rpms'
        subscription-manager repos --enable 'rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms'
      when: registration.changed

    - yum:
        name="{{ sat_installer_pkg }}"
        state=present
      register: installation
    - command:
        "{{ sat_installer_cmd }} --foreman-admin-email {{ sat_email }} --foreman-admin-username {{ sat_user }} --foreman-admin-password {{ sat_pass }}"
      when: installation.changed

    - copy: src=files/manifest.zip dest=/root/
      register: manifest_copied
    - command:
        hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' subscription upload --organization 'Default Organization' --file /root/manifest.zip
      when: manifest_copied.changed

    - shell: |
        hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' repository-set enable --product '{{ product1 }}' --name '{{ reposet1 }}' --basearch '{{ ansible_architecture }}' --releasever '{{ releasever }}' --organization-id '{{ orgid }}'
        hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' repository-set enable --product '{{ product2 }}' --name '{{ reposet2 }}' --basearch '{{ ansible_architecture }}' --releasever '{{ releasever }}' --organization-id '{{ orgid }}'
        hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' repository-set enable --product '{{ product3 }}' --name '{{ reposet3 }}' --basearch '{{ ansible_architecture }}' --releasever '{{ releasever }}' --organization-id '{{ orgid }}'
      when: manifest_copied.changed
      register: repos_enabled

    - shell: |
        hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' repository synchronize --product '{{ product1 }}' --name '{{ reposet1 }} {{ ansible_architecture }} {{ releasever }}' --organization-id '{{ orgid }}'
        hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' repository synchronize --product '{{ product2 }}' --name '{{ reposet2 }} {{ ansible_architecture }} {{ releasever }}' --organization-id '{{ orgid }}'
        hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' repository synchronize --product '{{ product3 }}' --name '{{ reposet3 }} {{ ansible_architecture }} {{ releasever }}' --organization-id '{{ orgid }}'
      when: repos_enabled.changed
