---
- name: "Configure larger ARP table"
  ansible.posix.sysctl:
    sysctl_file: "/etc/sysctl.d/50-enlarge-arp-table.conf"
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    reload: True
  loop: "{{ common_sysctl_config_default | dict2items }}"
...
