---
- hosts: capsules
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    ###- common-eth1
    - common
    - rhsm-satellite
    - ntp
    ###- upgrade-restart
    ###- capsule-ec2-partitioning
    - capsule
    ###- capsule-myrhev-partitioning
    - capsule-populate
    - pbench_client
