---
- hosts: satellite6
  remote_user: "{{ satperf_remote_user }}"
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - client-content
...
