---
- hosts: docker-hosts
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - common
    - docker-host-kvm-partitioning
    ###- docker-host-ec2-partitioning
    - rhsm
    ###- upgrade-restart
    - docker-host
...
