---
- hosts: docker-hosts
  remote_user: root
  roles:
  ###  - common
  tasks:
    - name: "Count running containers"
      shell:
        docker ps -q | wc -l
      register: docker_ps_wc
    - name: "There are no runing containers"
      shell:
        docker kill $( docker ps -q )
      when: docker_ps_wc.stdout|int > 0
    - name: "Count stopped containers"
      shell:
        docker ps -qa | wc -l
      register: docker_psa_wc
    - name: "There are no images"
      shell:
        docker rm $( docker ps -aq )
      when: docker_psa_wc.stdout|int > 0
    - name: "Docker daemon is restarted"
      service:
        name=docker
        state=restarted
    - name: "Container's yum caches are removed"
      file:
        name=/tmp/yum-cache
        state=absent
    - name: "Empty contailer's yum cache created"
      file:
        name=/tmp/yum-cache
        state=directory
    - name: "Caches are dropped"
      shell:
        echo 3 > /proc/sys/vm/drop_caches
