---
- hosts: docker-hosts
  remote_user: root
  tasks:
    - name: "Service docker is running"
      service:
        name=docker
        state=restarted
    - name: "Containers are started"
      shell: |
        for c in $( docker ps -qa ); do
          docker start $c
        done
