---
- hosts: all
  gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  tasks:
    - name: "Flush ebtables to fix routing"
      command:
        ebtables -t nat --flush
...
