---
- hosts: satellite
  remote_user: "{{ satperf_remote_user }}"
  roles:
    - add-product
    - backup
    - content-view
    - create-lifecycle
    - enable-content
    - register
    - restore
    - sync
