---
- hosts: satellite6
  gather_facts: False
  tasks:
    - name: "Create OS"
      shell:
        hammer os create --architectures x86_64 --family Redhat --name "{{ containers_os.name }}" --major "{{ containers_os.major }}" --minor "{{ containers_os.minor }}"
      ignore_errors: yes
    - name: "Create Hostgroup"
      shell:
        hammer hostgroup create --content-view "{{ organization }} View" --lifecycle-environment Library --name "{{ hostgroup_name }}" --query-organization "{{ organization }}" --subnet "{{ subnet_name }}" --operatingsystem "{{ containers_os.name }} {{ containers_os.major}}.{{containers_os.minor}}" --group-parameters-attributes "name=kt_activation_keys\,value=ActivationKey"
...
