---
- hosts: satellite6
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - common
    - rhsm
    - ntp
    ###- upgrade-restart
    ###- satellite-ec2-partitioning
    - setup
    - pbench_client
    - satellite-populate
...
