---
- name: "Make sure we have basic facts needed by linux-system-roles.network"
  setup:
    gather_subset: min
  when: ansible_python is not defined

- name: "Showing config"
  debug:
    msg:
      - "Public network: {{ public_nic }} with {% if public_ip is not defined %}DHCP{% else %}{{ (public_ip + '/' + public_netmask) | ansible.utils.ipaddr('host/prefix') }}{% endif %}"
      - "Private network: {{ private_nic }} with {{ (private_ip + '/' + private_netmask) | ansible.utils.ipaddr('host/prefix') }}"

- name: "Setup networking"
  include_role:
    name: linux-system-roles.network
  vars:
    network_allow_restart: yes
    network_connections: "{{ plain_network_yaml|from_yaml }}"
...
