---
roles:
  - name: linux-system-roles.timesync
  
  - name: linux-system-roles.firewall

  - name: rhsm_helper
    src: https://github.com/jhutar/ansible-role-rhsm_helper.git
    version: origin/main

collections: []
...
