---
    - command:
        pbench_config && \
          pbench-user-benchmark \
                --config=$tname-cv-promote-seq \
                -- "./scripts/cv_promote_seq.sh" && \
          pbench_postprocess
      register: content_view_promote_seq
      when: promote_seq == true

    - command:
        pbench_config && \
          pbench-user-benchmark \
                --config=$tname-cv-promote-concurrent \
                -- "./scripts/cv_promote_conc.sh" && \
          pbench_postprocess
      register: content_view_promote_conc
      when: promote_conc == true
...
