- hosts: satellite6
  remote_user: root
  gather_facts: no
  tasks:
    - name: download the storage-benchmark script
      get_url:
        url: https://github.com/RedHatSatellite/satellite-support/blob/master/storage-benchmark
        dest: /root
        mode: '0755'
    - name: run the storage-benchmark script
      command:
        cmd: ./storage-benchmark /var/lib/pulp -y >> results.log
    - name: check tuned profile
      command: "{{item}}"
      with_items:
       - service tuned start >> results.log
       - tuned-adm profile throughput-performance >> results.log
       - tuned-adm profile virtual-guest >> results.log
    - name: update custom-hiera.yaml file with httpd,qdrouterd tunings,passenger
      lineinfile:
      path:  /etc/foreman-installer/custom-hiera.yaml
      line: "{{ item.line }}"
      with_items: 
        - 'apache::mod::prefork::serverlimit: 582'
        - 'apache::mod::prefork::maxclients: 582'
        - 'apache::mod::prefork::startservers: 10'
        - 'qpid::router::open_file_limit: 150100'
        - 'qpid::open_file_limit: 65536'
        - 'apache::mod::passenger::passenger_max_pool_size: 48'
        - 'apache::mod::passenger::passenger_max_request_queue_size: 400'
    - name: update custom-hiera.yaml file with postgresql 
      blockfile: 
      path: /etc/foreman-installer/custom-hiera.yaml
      block: |
            postgresql::server::config_entries:
                max_connections: 1000
                shared_buffers: 2GB
                work_mem: 8MB
                checkpoint_segments: 32
                autovacuum_vacuum_cost_limit: 2000
    - name: update limits.conf file 
      lineinfile:
      path:  /etc/systemd/system/httpd.service.d/limits.conf
      line: "{{ item.line }}"
      with_items: 
       - [Service]
       - LimitNOFILE=640000
    - name: update dynflowd tuning 
      lineinfile:
      path:  /etc/sysconfig/dynflowd
      line: EXECUTORS_COUNT=2
    - name: restart the satellite
     command: "{{item}}"
     with_items:
      - satellite-installer
      - systemctl daemon-reload
      - foreman-maintain service restart
    - name: download the storage-benchmark script
     get_url:
       url: https://github.com/RedHatSatellite/satellite-support/blob/master/postgres-size-report
       dest: /root
       mode: '0755'
    - name: run the postgres-size-report  script
      command:
        cmd: ./postgres-size-report >> results.log      
    

