---
- name: "Detect RHEL release"
  setup:
    filter: ansible_distribution_major_version
  when: ansible_distribution_major_version is not defined

- name: 'This is RHEL7'
  import_tasks: rhel7.yaml
  when: ansible_distribution_major_version == 7

- name: 'This is RHEL8'
  import_tasks: rhel8.yaml
  when: ansible_distribution_major_version == 8
...
