---
orgid: 1
releasever: "7Server"
product1: "Red Hat Enterprise Linux Server"
product2: "Red Hat Enterprise Linux Server"
product3: "Red Hat Software Collections for RHEL Server"
reposet1: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server (RPMs)"
reposet2: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server - RH Common (RPMs)"
reposet3: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server"
repo1: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server RPMs x86_64 {{ releasever }}"
repo2: "Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server - RH Common RPMs x86_64 {{ releasever }}"
repo3: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux {{ ansible_distribution_major_version }} Server x86_64 {{ releasever }}"
...
