---
- name: "Upgrade"
  yum:
    name: '*'
    state: latest
  register: yum_upgrade_cmd

- name: "Show upgrade result"
  debug:
    var: yum_upgrade_cmd

- name: "Make sure we have needs-restarting utility"
  yum:
    name: yum-utils
    state: present

- name: "Check if reboot is necessary"
  command: needs-restarting -r
  register: needs_restarting_cmd
  changed_when: false
  failed_when: "needs_restarting_cmd.rc not in [0, 1]"

- name: "Reboot"
  reboot:
  when: "needs_restarting_cmd.rc == 1"
...
