---
- name: "Detect RHEL release"
  ansible.builtin.setup:
    filter: ansible_distribution_major_version
  when: ansible_distribution_major_version is not defined

# RHEL8 requirements
- name: "Enable satellite:el8 module"
  command: dnf -y module enable satellite:el8
  when: "ansible_distribution_major_version | int == 8"

# Install packages required for Satellite
- name: "Install satellite package"
  ansible.builtin.dnf:
    name: "satellite"
    state: present

# Figure out installer options
- name: "Determine base installer options"
  ansible.builtin.set_fact:
    sat_installer_opts: "--foreman-initial-admin-username {{ sat_user | default('admin') }} --foreman-initial-admin-password {{ sat_pass }}"

- name: "Determine Installer command line"
  ansible.builtin.set_fact:
    sat_installer_cmd_line: "satellite-installer --scenario satellite {{ sat_installer_opts }}"

- name: "Configure Insights connection"
  ansible.builtin.set_fact:
    sat_installer_cmd_line: "{{ sat_installer_cmd_line }} --foreman-proxy-plugin-remote-execution-script-install-key true"
  when:
    - setup_insights is not defined or not setup_insights

- name: "Configure MQTT transport for remote execution"
  ansible.builtin.set_fact:
    sat_installer_cmd_line: "{{ sat_installer_cmd_line }} --foreman-proxy-plugin-remote-execution-script-mode pull-mqtt"
  when:
    - rex_mode is defined and rex_mode == 'mqtt'

- name: "Ensure sat_version is string to avoid hard to detect issues"
  ansible.builtin.assert:
    that: sat_version is string
    fail_msg: "Variable 'sat_version' have to be string to avoid issues like one when we had 6.10 version interpretted as 6.1 (trailing '0' removed as it was interpreted as number)"

- name: "Run desired shell commands before installation"
  ansible.builtin.shell:
    cmd: "{{ run_before_sat_installer }}"
  when:
    - run_before_sat_installer is defined and run_before_sat_installer | length > 0

- name: "Show Installer command line"
  debug:
    msg: "{{ sat_installer_cmd_line }}"

# Run the installer
- name: "Run Satellite configuration"
  shell: "{{ sat_installer_cmd_line }}"
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    TZ: "UTC"
  register: satellite_installer_cmd

- name: "Show Satellite configuration output"
  ansible.builtin.debug:
    var: satellite_installer_cmd.stdout_lines

- name: "Print installer run duration"
  debug:
    msg: "SatelliteInstallerScenarioSatellite {{ satellite_installer_cmd.start }} to {{ satellite_installer_cmd.end }} taking {{ satellite_installer_cmd.delta }} seconds"

- name: "Run desired shell commands after installation"
  ansible.builtin.shell:
    cmd: "{{ run_after_sat_installer }}"
  when:
    - run_after_sat_installer is defined and run_after_sat_installer | length > 0

- name: "Workaround for: Bug 2132774 - On its default configuration mosquitto cannot accept more than 1014 clients"
  ansible.builtin.copy:
    content: |
      [Service]
      LimitNOFILE=infinity
    dest: /etc/systemd/system/mosquitto.service.d/limits.conf
    mode: '0444'
  when:
    - rex_mode is defined and rex_mode == 'mqtt'

- name: Restart mosquitto service unit
  ansible.builtin.systemd_service:
    name: mosquitto
    daemon_reload: true
    state: restarted
  when:
    - rex_mode is defined and rex_mode == 'mqtt'
...
