---
    - copy:
        src="{{ sat_repo_file }}"
        dest=/etc/yum.repos.d/
    - yum:
        name="{{ sat_installer_pkg }}"
        state=present
      register: installation
    - command:
        "{{ sat_installer_cmd }} --foreman-admin-email {{ sat_email }} --foreman-admin-username {{ sat_user }} --foreman-admin-password {{ sat_pass }}"
      when: installation.changed
...
