---
  - name: "Make sure libvirt & comp. is present"
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - libvirt
      - qemu-kvm
      - libvirt-python
      - virt-install
  - name: "Make sure libvirtd is running"
    service:
      name: libvirtd
      state: started
...
