---
#
# Playbook to install the ELK stack
#

- hosts: elk
  remote_user: "{{ satperf_remote_user }}"
  roles:
    - { role: elasticsearch }
    - { role: logstash }
    - { role: nginx }
    - { role: kibana }
