---
#
# Playbook to install grafana
#

- hosts: grafana
  remote_user: "{{ satperf_remote_user }}"
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - role: ../satellite/roles/rhsm
      when:
        - offline_install is undefined
        - "groups['graphite']|first != groups['grafana']|first"
    - { role: grafana }
