---
  - name: "Create physical volumes and volume group"
    lvg:
      vg: guest_images_lvm
      pvs: "{{ vms_storage_pvs | default('/dev/sdb') }}"
  - name: "Define storage pool"
    virt_pool:
      name: guest_images_lvm
      command: define
      xml:  "{{ lookup('template', 'files/guest_images_lvm.xml.j2') }}"
  - name: "Make sure storage pool have autostart enabled"
    virt_pool:
      name: guest_images_lvm
      autostart: yes
  - name: "Make sure storage pool is active"
    virt_pool:
      name: guest_images_lvm
      state: active
...
