---
  #- name: "Cleanup possible existing VGs and PVs"
  #  shell: |
  #      vgremove docker
  #      vgremove vg_docker
  #      pvremove /dev/sdb
  #      if fdisk -l /dev/sdb | grep '/dev/sdb1'; then
  #          pvremove /dev/sdb1
  #          echo -e "d\nw" | fdisk /dev/sdb
  #          partprobe
  #      fi
  #  ignore_errors: True

  - name: "Create physical volumes and volume group"
    lvg:
      vg: guest_images_lvm
      pvs: "{{ vms_storage_pvs | default('/dev/sdb') }}"
  - name: "Define storage pool"
    virt_pool:
      name: guest_images_lvm
      command: define
      xml:  "{{ lookup('template', 'files/guest_images_lvm.xml.j2') }}"
  - name: "Make sure storage pool have autostart enabled"
    virt_pool:
      name: guest_images_lvm
      autostart: yes
  - name: "Make sure storage pool is active"
    virt_pool:
      name: guest_images_lvm
      state: active
...
