---
- ansible.builtin.yum:
    name: lvm2
    state: present
  when: ansible_distribution_major_version | int == 7
- ansible.builtin.dnf:
    name: lvm2
    state: present
  when: ansible_distribution_major_version | int >= 8
- setup:
    gather_subset:
      - '!all'
      - hardware
- include_tasks: remove_home_partition.yaml
  when: 'remove_home_partition|bool == True'
- include_tasks: extend_root_partition.yaml
  when: 'extend_root_partition|bool == True'
...
