---
- hosts: satellite6 capsules container_hosts
  gather_facts: False
  roles:
    - role: ../common/roles/epel-not-present
    - role: ../common/roles/scalelab-generic-cleanup
      when: '"scalelab" in inventory_hostname'
    - role: ../common/roles/plain-network
      when:
        - configure_plain_network is defined and configure_plain_network | bool == True
    - role: ../common/roles/common
...
