---
- hosts: all
  gather_facts: False
  roles:
    - ../common/roles/scalelab-nic-cleanup
    - ../common/roles/common
    - ../common/roles/remove-home-extend-root
    - ../common/roles/epel-not-present
    - ../common/roles/rhsm
    - linux-system-roles.timesync
...
