---
  # TODO Would be great if we would create one location per capsule and add
  # capsule to it. It is important for Remote Execution because if client
  # system is in default location, it should have ssh key of all capsules in
  # that location
  - name: "Set organization and location"
    command:
      "hammer -u {{ sat_user }} -p {{ sat_pass }} capsule update --name {{ item }} --organizations '{{ sat_org }}' --locations '{{ sat_location }}'"
    delegate_to: "{{ groups['satellite6']|first }}"
    run_once: true
    with_items: "{{ groups['capsules'] }}"
  - name: "Add '*' autosign entry"
    command:
      "true"
    delegate_to: "{{ groups['satellite6']|first }}"
    run_once: true
    with_items: "{{ groups['capsules'] }}"
  - name: "Assign Library"
    command:
      "hammer -u {{ sat_user }} -p {{ sat_pass }} capsule content add-lifecycle-environment --name {{ item }} --organization '{{ sat_org }}' --environment Library"
    delegate_to: "{{ groups['satellite6']|first }}"
    run_once: true
    with_items: "{{ groups['capsules'] }}"
  - name: "Sync"
    command:
      "hammer -u {{ sat_user }} -p {{ sat_pass }} capsule content synchronize --name {{ item }} --organization '{{ sat_org }}' --environment Library --async"
    delegate_to: "{{ groups['satellite6']|first }}"
    run_once: true
    with_items: "{{ groups['capsules'] }}"
  #- name: "Set autosign"
  #  ### TODO https://bugzilla.redhat.com/show_bug.cgi?id=1140671
...
