---
- name: "Assign capsule to organization '{{ organization }}'"
  ansible.builtin.command:
    cmd: "hammer -u {{ sat_user }} -p {{ sat_pass }} capsule update --name {{ inventory_hostname }} --organizations '{{ organization }}'"
  delegate_to: "{{ groups['satellite6']|first }}"

- name: "Set capsule download policy to immediate"
  ansible.builtin.command:
    cmd: "hammer -u {{ sat_user }} -p {{ sat_pass }} capsule update --name {{ inventory_hostname }} --download-policy immediate"
  delegate_to: "{{ groups['satellite6']|first }}"

- name: "Assign Library lifecycle environment"
  ansible.builtin.shell: |
    if hammer --no-headers --output csv -u {{ sat_user }} -p {{ sat_pass }} capsule content lifecycle-environments --name '{{ inventory_hostname }}' --organization '{{ organization }}' --fields name | grep '^Library$'; then
      echo "Library already present in {{ inventory_hostname }}"
    else
      hammer -u {{ sat_user }} -p {{ sat_pass }} capsule content add-lifecycle-environment --name '{{ inventory_hostname }}' --organization '{{ organization }}' --lifecycle-environment Library
    fi
  delegate_to: "{{ groups['satellite6']|first }}"
  register: hammer_add_le_to_capsule_cmd
  changed_when: "hammer_add_le_to_capsule_cmd.rc is defined and hammer_add_le_to_capsule_cmd.rc == 0 and 'Library already present in ' + inventory_hostname not in hammer_add_le_to_capsule_cmd.stdout"

- name: "Sync the content"
  ansible.builtin.command:
    cmd: "hammer -u {{ sat_user }} -p {{ sat_pass }} capsule content synchronize --organization '{{ organization }}' --name {{ inventory_hostname }} --lifecycle-environment Library --skip-metadata-check true"
  delegate_to: "{{ groups['satellite6']|first }}"
...
