---
- hosts: all
  gather_facts: false
  tasks:
    - name: Detect RHEL release
      ansible.builtin.setup:
        filter: ansible_distribution_major_version
      when: ansible_distribution_major_version is not defined

    - name: Set AK name
      ansible.builtin.set_fact:
        ak: "AK_rhel{{ ansible_distribution_major_version }}_Test"

    - name: Cleanup
      ansible.builtin.shell:
        cmd: |
          rm -f /etc/yum.repos.d/*.repo

    - name: Upload script to content host
      ansible.builtin.copy:
        src: /root/host-registration.{{ ak }}.sh
        dest: /root/host-registration.sh
        mode: '0500'

    - name: Register
      ansible.builtin.shell:
        cmd: |
          set -o pipefail

          /root/host-registration.sh &>/root/registration.log
          ret=$?

          echo "-" >>/root/registration.log
          echo "Return code: $ret" >>/root/registration.log
          echo "-----" >>/root/registration.log

          cat /root/registration.log
          exit $ret
      environment:
        TZ: UTC   # make sure returned times are in UTC
      register: reg

    - name: "Register - output"
      ansible.builtin.debug:
        var: reg.stdout_lines

    - name: "Register - timings"
      ansible.builtin.debug:
        msg: "Register {{ reg.start }} to {{ reg.end }}"
      when: "reg.rc == 0"

    - name: "Disable insights-client automatic scheduling"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail

          if [[ -x /usr/bin/insights-client ]]; then
              insights-client --disable-schedule
          fi

    - name: "Enable and start rhsmcertd systemd service unit"
      ansible.builtin.systemd_service:
        name: rhsmcertd
        state: started
        enabled: true
...
