---
  # Enable repositories
  - name: "List repositories we already have (not to attempt to enable what we already have)"
    command:
      hammer --csv --username '{{ sat_user }}' --password '{{ sat_pass }}' repository list --organization '{{ sat_org }}'
    register: repository_list
  - include: try_enable_repo.yaml
    when: 'repository_list.stdout.find(",{{ item.repo }},") == -1'
    with_items:
      "{{ soak_repos }}"

  # Start async of the repos
  - name: "Start (asynchronous) sync of repos we have just enabled"
    command:
      hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' repository synchronize --product '{{ item.product }}' --name '{{ item.repo }}' --organization '{{ sat_org }}' --async
    with_items:
      "{{ soak_repos }}"
...
