---
- hosts: kvm-hosts
  remote_user: root
  gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - ../satellite/roles/scalelab-nic-cleanup
    - ../satellite/roles/rhsm
    - setup-bridges
    - install-libvirtd
    - setup-storage
...
