---
  - name: Get the repository id
    set_fact:
      repo: "{{ item.0.stdout | from_json }}"
  - name: Set the repository id
    set_fact:
      repoid: "{{ repo_item.ID }}"
    with_items: "{{ repo }}"
    loop_control:
      loop_var: repo_item
  - name: Attach to the content view
    shell:
      hammer --username "{{ sat_user }}" --password "{{ sat_pass }}" content-view add-repository --name "{{ item.1.name }}" --organization "Default Organization" --repository-id "{{ repoid }}"
  - debug:
      var: repoid 
...
