---
  - get_url:
      url="{{ pbench_repo_file }}"
      dest=/etc/yum.repos.d/pbench.repo

  - yum:
      name=pbench-agent
      state=present

  ## TODO: I assume we can delete this?
  #- shell:
  #    source /opt/pbench-agent/config
...
