---
- name: "Distribute client registration script"
  throttle: 8
  ansible.builtin.copy:
    src: "clients_host-registration.yaml"
    dest: "/root/clients_host-registration.yaml"
    force: yes

- name: "Install Ansible (in RHEL <8.6)"
  throttle: 8
  ansible.builtin.package:
    name: ansible
    state: present
  when: "ansible_distribution_version is version('8.6', '<')"

- name: "Install Ansible (in RHEL >=8.6)"
  throttle: 8
  ansible.builtin.package:
    name: ansible-core
    state: present
  when: "ansible_distribution_version is version('8.6', '>=')"

- name: "Ensure we have Ansible config with default section"
  throttle: 8
  ansible.builtin.lineinfile:
    dest: /etc/ansible/ansible.cfg
    insertafter: EOF
    line: '[defaults]'
    state: present

- name: "Ansible should not check host keys"
  throttle: 8
  lineinfile:
    dest: /etc/ansible/ansible.cfg
    regexp: '^.*host_key_checking'
    insertafter: '[defaults]'
    line: 'host_key_checking = False'
    state: present

- name: "Distribute private key"
  throttle: 8
  copy:
    src: "../../{{ client_private_key }}"
    dest: /root/id_rsa_key
    mode: "u=rw,g=,o="
    force: yes
...
