---
- name: "Distribute client registration script"
  throttle: 8
  ansible.builtin.copy:
    src: "clients_host-registration.yaml"
    dest: "/root/clients_host-registration.yaml"
    force: yes

- name: "Install Ansible"
  throttle: 8
  ansible.builtin.dnf:
    name: ansible-core
    state: latest

- name: "Ensure we have Ansible config with default section"
  throttle: 8
  ansible.builtin.lineinfile:
    dest: /etc/ansible/ansible.cfg
    insertafter: EOF
    line: '[defaults]'
    state: present

- name: "Ansible should not check host keys"
  throttle: 8
  ansible.builtin.lineinfile:
    dest: /etc/ansible/ansible.cfg
    regexp: '^.*host_key_checking'
    insertafter: '[defaults]'
    line: 'host_key_checking = False'
    state: present

- name: "Distribute private key"
  throttle: 8
  ansible.builtin.copy:
    src: "../../{{ ansible_ssh_private_key_file }}"
    dest: /root/id_rsa_key
    mode: "u=rw,g=,o="
    force: true
...
