---
  # Add '*' autosign entry to Puppet CA of integrated capsule
  - name: "If file exists, it is enabled"
    ansible.builtin.stat:
      path: /etc/puppetlabs/puppet/autosign.conf
    register: stat_result
    when: "sat_version == 'stream' or sat_version is ansible.builtin.version('6.11.0', '>=')"

  - name: "Add '*' autosign entry (Satellite 6.11 and above)"
    ansible.builtin.lineinfile:
      path: "/etc/puppetlabs/puppet/autosign.conf"
      line: "*"
    when:
      - sat_version == 'stream' or sat_version is ansible.builtin.version('6.11.0', '>=')
      - stat_result.stat.exists
...
