---
- hosts: physical-clients[1:10]
  remote_user: root
  gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  pre_tasks:
    - name: "Gather facts"
      setup:
        gather_subset:
            - '!all'
      retries: 3
      delay: 3
      register: result
      until: not result.failed
  roles:
    - ../common/roles/common
    - ../common/roles/rhsm-satellite
  tasks:
    - name: "Deploy remote execution SSH key"
      authorized_key:
        user: root
        state: present
        key: "https://{{ groups['satellite6']|first }}:9090/ssh/pubkey"
        validate_certs: no
      retries: 3
      delay: 3
      register: result
      until: not result.failed
